### ISSUE TITLE
Executing solidity-coverage via NodeJS

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#470]
Up until v0.7.x, one could execute solidity-coverage via node script, for example:
```
const WORK_DIR = "./project";
const NODE_DIR = "../node_modules";

const spawn = require("child_process").spawn;

const cp = spawn("node", [NODE_DIR + "/solidity-coverage/bin/exec.js"], {cwd: WORK_DIR});
cp.stdout.on("data", function(data) {process.stdout.write(data.toString());});
cp.stderr.on("data", function(data) {process.stderr.write(data.toString());});
cp.on("error", function(error) {process.stderr.write(error.toString());});
```
After upgrading to v0.7.0, I tried replacing `bin/exec.js` with`plugins/buidler.plugin.js`, but received:
```
Error: Cannot find module '@nomiclabs/buidler/internal/core/providers/construction'
```
It is critical for us to be able to automate our usage of solidity-coverage via node, because it masks out any platform dependency (in contrast with executing `sh` or `bat` scripts). Is there any way for us to do so in the same manner that we have up until v0.6.7?

Thanks

**Comment by cgewecke** [comment]
@barakman Some quick questions. Are you using Buidler? Do you have a code branch you're experimenting with 0.7.0 on?

0.7.0 involved a decision to restructure the tool [as an API][1] and produce plugin versions that consume it for existing dev tooling (like Truffle). The intent was to de-couple the tool from any specific stack and make it possible for people to build whatever they need. 

If you are using Buidler or Truffle, could you spawn the plugin based command, e.g.
`truffle run coverage` or `buidler coverage`? 

 [1]:  https://github.com/sc-forks/solidity-coverage/blob/master/docs/api.md#solidity-coverage-api

**Comment by barakman** [comment]
@cgewecke : Thank you for your very quick response!

I am using [this script](https://github.com/bancorprotocol/contracts/blob/master/scripts/run-tests.js), which allows me to execute:
- ganache-cli + truffle test via `npm test 1`
- testrpc-sc + solidity-coverage via `npm test 2`

This infrastructure allows the system to be 100% platform-agnostic (isn't that great?).

It also allows the user to start each one of these two processes very easily ("in a single key-press").

I understand from your [Upgrading from 0.6.x to 0.7.x Guide](https://github.com/bancorprotocol/contracts/blob/master/scripts/run-tests.js) that `testrpc-sc` is out and I should simply use `ganache-cli`; that one is easy.

But how do I get the "old solidity-coverage" command executed?

My method up until now has been to run `bin/exec.js`.

What part in your code embeds this file?

Or what other ways could you suggest for me to use instead?

**Comment by cgewecke** [comment]
@barakman If you're staying on Truffle 4, and you're not contemplating migrating to Buidler's using their [Truffle4 packages][3], I think you will have to write a script using the API (unfortunately). 

This is because the plugins rely on the dev tooling exposing things like the compile and test commands via their plugin APIs. 

If you *were* upgrading, the modification would probably look something like this on [line 42][1] (or its Buidler equivalent).
```diff
- SOL_COVERAGE: [NODE_DIR + "/solidity-coverage/bin/exec.js"       ],
+ SOL_COVERAGE: ["/truffle/build/cli.bundled.js", "run", "coverage"],
```

Then, you would just let the plugin launch ganache itself.  The only additional thing you might need to do is configure the accounts and their balances correctly using the ganache-core `providerOptions` key which can be defined in `.solcover.js`. (see [config options][2]). You might also specify which ganache version to use there, like this:

```javascript
module.exports = {
  client: require('ganache-cli'),
  providerOptions: {
     ..etc..
  }
}
```

Are you committed to staying with your tooling existing setup? You don't have much in the way of migrations so Buidler might be worth exploring to see if you can get the basic test command passing.

[1]: https://github.com/bancorprotocol/contracts/blob/0e03a812681b67163eef32cfd85140c6117e2b62/scripts/run-tests.js#L42
[2]: https://github.com/sc-forks/solidity-coverage#config-options
[3]: https://github.com/nomiclabs/buidler/tree/master/packages/buidler-truffle4#buidler-truffle4

**Comment by cgewecke** [comment]
Closing. For future reference the JS API docs are [here][1]

[1]: https://github.com/sc-forks/solidity-coverage/blob/master/docs/api.md#solidity-coverage-api
